name: Build

on: [push] #, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04] #, windows-latest, macos-latest]

    env:
      CIBW_SKIP: cp27-* pp27-*
      CIBW_BEFORE_BUILD_LINUX: |
        yum install -y  \
          java-1.8.0-openjdk-devel \
          libXrandr-devel \
          libXi-devel \
          libXcursor-devel \
          libX11-devel \
          xorg-x11-devel \
          libXcursor
        # Why the fuck is there no headless-devel package like on debian!
        
      CIBW_BEFORE_BUILD: pip install .

    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - uses: actions/setup-java@v1.3.0 # This is for MacOS and Windows
        with:
          java-version: '8' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64


      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.5.2


      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl